"""hybrid_sharing_model

Revision ID: 004
Revises: 003
Create Date: 2026-05-23 13:58:51.079829

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "004"
down_revision: Union[str, Sequence[str], None] = "003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "outputs", "storage_path", existing_type=sa.VARCHAR(), nullable=True
    )
    op.add_column("papers", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.add_column(
        "papers",
        sa.Column("is_public", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "papers", sa.Column("published_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###

    # --- Add Row Level Security ---
    # 1. Enable RLS on all tables
    tables = [
        "papers",
        "extractions",
        "embeddings",
        "outputs",
        "pipeline_runs",
        "stage_results",
    ]
    for table in tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")

    # 2. Add Policies to papers
    op.execute(
        """
        CREATE POLICY "private_access" ON papers
        FOR SELECT TO authenticated USING (user_id = auth.uid());
        """
    )
    op.execute(
        """
        CREATE POLICY "public_access" ON papers
        FOR SELECT TO authenticated USING (is_public = TRUE);
        """
    )

    # 3. Add Policies to output tables (that have paper_id directly)
    output_tables = ["extractions", "embeddings", "outputs", "pipeline_runs"]
    for table in output_tables:
        op.execute(
            f"""
            CREATE POLICY "output_private_access" ON {table}
            FOR SELECT TO authenticated USING (
                EXISTS (
                    SELECT 1 FROM papers
                    WHERE papers.id = {table}.paper_id
                    AND papers.user_id = auth.uid()
                )
            );
            """
        )
        op.execute(
            f"""
            CREATE POLICY "output_public_access" ON {table}
            FOR SELECT TO authenticated USING (
                EXISTS (
                    SELECT 1 FROM papers
                    WHERE papers.id = {table}.paper_id
                    AND papers.is_public = TRUE
                )
            );
            """
        )

    # 4. Add Policies to stage_results (needs to join through pipeline_runs)
    op.execute(
        """
        CREATE POLICY "output_private_access" ON stage_results
        FOR SELECT TO authenticated USING (
            EXISTS (
                SELECT 1 FROM pipeline_runs
                JOIN papers ON pipeline_runs.paper_id = papers.id
                WHERE pipeline_runs.id = stage_results.run_id
                AND papers.user_id = auth.uid()
            )
        );
        """
    )
    op.execute(
        """
        CREATE POLICY "output_public_access" ON stage_results
        FOR SELECT TO authenticated USING (
            EXISTS (
                SELECT 1 FROM pipeline_runs
                JOIN papers ON pipeline_runs.paper_id = papers.id
                WHERE pipeline_runs.id = stage_results.run_id
                AND papers.is_public = TRUE
            )
        );
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Drop Policies
    output_tables = [
        "extractions",
        "embeddings",
        "outputs",
        "pipeline_runs",
        "stage_results",
    ]
    for table in output_tables:
        op.execute(f'DROP POLICY IF EXISTS "output_public_access" ON {table};')
        op.execute(f'DROP POLICY IF EXISTS "output_private_access" ON {table};')
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")

    op.execute('DROP POLICY IF EXISTS "public_access" ON papers;')
    op.execute('DROP POLICY IF EXISTS "private_access" ON papers;')
    op.execute("ALTER TABLE papers DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "published_at")
    op.drop_column("papers", "is_public")
    op.drop_column("papers", "user_id")
    op.alter_column(
        "outputs", "storage_path", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
